# Generated by Django 4.2 on 2026-04-12 14:30

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("db", "0122_chat_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="usernotificationpreference",
            name="chat_mention",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="usernotificationpreference",
            name="dm_received",
            field=models.BooleanField(default=True),
        ),
    ]
