# Generated by Django 4.2 on 2026-04-13 00:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("db", "0123_chat_notification_prefs"),
    ]

    operations = [
        migrations.AddField(
            model_name="channel",
            name="can_create_channels",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="channel",
            name="can_manage_members",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="channel",
            name="can_post",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="message",
            name="reply_to",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="quoted_replies",
                to="db.message",
            ),
        ),
    ]
